### ISSUE TITLE
How to get current user by accessToken

### ISSUE THREAD

**Issue by seantcam** [Authing/sdk-flutter#1]
Hello there,
I'm integrating Authing for our app authentication, I have already persisted accessToken after login succeed, but how to get current user by persisted accessToken? 

Thanks

**Comment by jiananMars** [comment]
Use Accesstoken to get user information: 

AuthResult result = await OIDCClient.getUserInfoByAccessToken("accessToken");
User user = result.user; // get user info

Documentation: 
https://pub.dev/packages/authing_sdk#token-change-user-information
